#################################################################################################################################################
# Example for controller settings. Would normally be stored as a .ERS asset on disk or in DB like all other ERS assets. Is set for each project #
#################################################################################################################################################

