# Set Logger configuration Parameters #
EnablePrintOutput: True
EnableDatabaseOutput: False

SetMinimumLogLevel: 0

# Set Window Configuration Parameters #
WindowEnabled: True
WindowWidth: 800
WindowHeight: 600
WindowTitle: "BrainGenix-ERS"
