###############################
# BrainGenix-ERS Project File #
###############################

EditorVersion: 0.0.2

ProjectName: "Example Project"
ProjectVersionMajor: 0
ProjectVersionMinor: 0
ProjectVersionPatch: 1